name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Run tests
      run: |
        echo "Running tests..."
        # This is a demo - in a real project, you would run actual tests
        python demo-files/sample-project.py
        echo "✅ All tests passed!"
    
    - name: Check file formatting
      run: |
        echo "Checking file formatting..."
        # Check if Python files are properly formatted
        python -m py_compile demo-files/sample-project.py
        echo "✅ Formatting looks good!"
    
    - name: Validate markdown files
      run: |
        echo "Validating markdown files..."
        # Check if markdown files exist and are readable
        find . -name "*.md" -type f -exec echo "Found: {}" \;
        echo "✅ Markdown files are valid!"
    
    - name: Check repository structure
      run: |
        echo "Checking repository structure..."
        # Verify that required directories exist
        test -d exercises && echo "✅ exercises/ directory exists"
        test -d demo-files && echo "✅ demo-files/ directory exists"
        test -d assets && echo "✅ assets/ directory exists"
        echo "✅ Repository structure is correct!"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to GitHub Pages (Demo)
      run: |
        echo "This would deploy to GitHub Pages in a real project"
        echo "For this demo, we're just showing the workflow structure"
        echo "✅ Deployment simulation complete!"
    
    - name: Create deployment summary
      run: |
        echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Tests passed" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Code quality checks passed" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Repository structure validated" >> $GITHUB_STEP_SUMMARY
        echo "- 🚀 Ready for deployment" >> $GITHUB_STEP_SUMMARY 